version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432" # host_machine:container
    volumes:
      # mounts a named docker volume postgres_data at 
      #/var/lib/postgresql/data inside the container to persist database data
      - postgres_data:/var/lib/postgresql/data

  # http interface to access psql
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "80:80"
    depends_on:
      - postgres

  mlflow:
    build: .
    ports:
      - "5000:5000"
    environment:
      MLFLOW_SQLALCHEMYSTORE_DATABASE_URI: postgresql://mlflow:mlflow@postgres:5432/mlflow
    
    # start mlflow server and listen to all ports
    command: ["mlflow", "server", "--host", "0.0.0.0"]
    # volumes:
    #   - ./mlruns:/mlflow/mlruns
    depends_on:
      # will start only after postgres service is started
      - postgres

volumes:
  postgres_data:
